Carritode ComprasAdmi/Controllers/TiendaController.cs
using CapaEntidades;
using CapaNegocio;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapaEntidades.PayPal;
using Carritode_ComprasAdmi.Filter;

namespace Carritode_ComprasAdmi.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult DetalleProducto(int IdProducto = 0)
        {
            Producto oProducto = new Producto();
            bool conversion;
            oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == IdProducto).FirstOrDefault();
            if (oProducto != null)
            {
                oProducto.Base64 = CN_Recursos.CovertirBase64(Path.Combine(oProducto.RutaImagen, oProducto.NombreImagen), out conversion);
                oProducto.Extension = Path.GetExtension(oProducto.NombreImagen);
            }
            return View(oProducto);
        }


        [HttpGet]
        public ActionResult ListarCategorias()
        {
            List<Categoria> lista = new List<Categoria>();
            lista = new CN_Categoria().Listar();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult ListarMarcaProducto(int IdCategoria)
        {
            List<Marca> lista = new List<Marca>();
            lista = new CN_Marca().ListarMarcaProducto(IdCategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public JsonResult ListarProducto(int IdCategoria, int IdMarca)
        {
            List<Producto> lista = new List<Producto>();
            bool conversion;

           
            lista = new CN_Producto().Listar()
            .Where(p => (IdCategoria == 0 || p.Categoria.IdCategoria == IdCategoria) &&
                (IdMarca == 0 || p.Marca.IdMarca == IdMarca) &&
                p.Stock > 0 && p.Activo)
                .Select(p => new Producto
                {
                    IdProducto = p.IdProducto,
                    Nombre = p.Nombre,
                    Descripcion = p.Descripcion,
                    Marca = p.Marca,
                    Categoria = p.Categoria,
                    Precio = p.Precio,
                    Stock = p.Stock,
                    RutaImagen = p.RutaImagen,
                    Base64 = CN_Recursos.CovertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                    Extension = Path.GetExtension(p.NombreImagen),
                    Activo = p.Activo
                })
           .ToList();


            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;
            return jsonresult;

        }


        [HttpPost]
        public ActionResult AgregarCarrito(int IdProducto)
        {
            int IdCliente = ((Cliente)Session["Cliente"]).IdCliente;
            bool Exixte = new CN_Carrito().ExisteCarrito(IdCliente, IdProducto);
            bool Respuesta = false;
            string nensaje = string.Empty;

            if (Exixte)
            {
                nensaje = "El producto ya existe en el carrito";
            }
            else
            {
                Respuesta = new CN_Carrito().OperacionCarrito(IdCliente, IdProducto, true, out nensaje);
            }

            return Json(new { Respuesta = Respuesta, Mensaje = nensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult CantidadCarrito()
        {
            int IdCliente = ((Cliente)Session["Cliente"]).IdCliente;
            int Cantidad = new CN_Carrito().CantidadCarrito(IdCliente);
            return Json(new { Cantidad = Cantidad }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ListarProductosCarrito()
        {
            List<Carrito> listaCarrito = new List<Carrito>();

            if (Session["Cliente"] != null)
            {
                int idCliente = ((Cliente)Session["Cliente"]).IdCliente;

                listaCarrito = new CN_Carrito().ListarProducto(idCliente)
                    .Select(oc => new Carrito()
                    {
                        oProducto = new Producto()
                        {
                            IdProducto = oc.oProducto.IdProducto,
                            Nombre = oc.oProducto.Nombre,
                            Marca = oc.oProducto.Marca,
                            Precio = oc.oProducto.Precio,
                            RutaImagen = oc.oProducto.RutaImagen,
                            Base64 = CN_Recursos.CovertirBase64(Path.Combine(oc.oProducto.RutaImagen, oc.oProducto.NombreImagen), out bool conversion),
                            Extension = Path.GetExtension(oc.oProducto.NombreImagen)
                        },
                        Cantidad = oc.Cantidad
                    })
                    .ToList();
            }

            return Json(new { data = listaCarrito }, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public ActionResult OperacionCarrito(int IdProducto, bool Sumar)
        {
            int IdCliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool Respuesta = false;
            string nensaje = string.Empty;
            Respuesta = new CN_Carrito().OperacionCarrito(IdCliente, IdProducto, true, out nensaje);
            return Json(new { Respuesta = Respuesta, Mensaje = nensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public ActionResult EliminarCarrito(int IdProducto)
        {
            int IdCliente = ((Cliente)Session["Cliente"]).IdCliente;
            bool Respuesta = false;
            string nensaje = string.Empty;
            Respuesta = new CN_Carrito().EliminarCarrito(IdCliente, IdProducto);
            return Json(new { Respuesta = Respuesta, Mensaje = nensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ObtenerDepartamento()
        {
            List<Departamento> oLista = new List<Departamento>();
            oLista = new CN_Ubicacion().ListarDepartamento();
            return Json(new { Lista = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult ObtenerProvincia(String IdDepartamento)
        {
            List<Provincia> oLista = new List<Provincia>();
            oLista = new CN_Ubicacion().ListarProvincia(IdDepartamento);
            return Json(new { Lista = oLista }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public ActionResult ObtenerDistrito(String IdDepartamento, String IdProvincia)
        {
            List<Distrito> oLista = new List<Distrito>();
            oLista = new CN_Ubicacion().ListarDistrito(IdDepartamento, IdProvincia);
            return Json(new { Lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [ValidarSesionAtribute]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
        {
            decimal total = 0;
            DataTable listaDetalleVenta = new DataTable();
            listaDetalleVenta.Locale = new CultureInfo("es-PE");
            listaDetalleVenta.Columns.Add("IdProducto", typeof(string));
            listaDetalleVenta.Columns.Add("Cantidad", typeof(int));
            listaDetalleVenta.Columns.Add("Total", typeof(decimal));

            List<Item> oListaItem = new List<Item>();

            foreach (Carrito oCarrito in oListaCarrito)
            {
                decimal subTotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oProducto.Precio;
                total += subTotal;

                oListaItem.Add(new Item() {
                    name = oCarrito.oProducto.Nombre,
                    quantity = oCarrito.Cantidad.ToString(),
                    unit_amount = new UnitAmount()
                    {
                        currency_code = "USD",
                        value = oCarrito.oProducto.Precio.ToString("G", new CultureInfo("es-PE"))
                    }
                });

                listaDetalleVenta.Rows.Add(new object[]
                {
                    oCarrito.oProducto.IdProducto,
                    oCarrito.Cantidad,
                    subTotal
                });
            }

            PurchaseUnit purchaseUnit = new PurchaseUnit()
            {
                amount = new Amount()
                {
                    currency_code = "USD",
                    value = total.ToString("G", new CultureInfo("es-PE")),
                    breakdown = new Breakdown()
                    {
                        item_total = new ItemTotal()
                        {
                            currency_code = "USD",
                            value = total.ToString("G", new CultureInfo("es-PE")),
                        }
                    }
                },
                description = "compra de articulo de mi tienda",
                items = oListaItem
            };

            Checkout_Order ocheckout_Order = new Checkout_Order()
            {
                intent = "CAPTURE",
                purchase_units = new List<PurchaseUnit>()
                {
                    purchaseUnit
                },
                application_context = new ApplicationContext
                {
                    brand_name = "MiTienda.com",
                    landing_page = "NO_PREFERENCE",
                    user_action = "PAY_NOW",
                    return_url = "https://localhost:44315/Tienda/PagoEfectuado",

Carritode ComprasAdmi/Views/Tienda/DetalleProducto.cshtml
@model CapaEntidades.Producto
@{
    ViewBag.Title = "DetalleProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="data:image/@Html.DisplayTextFor(m => m.Extension); base64,@Html.DisplayTextFor(m => m.Base64)" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1"> Marca : @Html.DisplayTextFor(m => m.Marca.Descripcion)</div>
                <h1 class="display-5 fw-bolder"> @Html.DisplayTextFor(m => m.Nombre)</h1>
                <div class="fs-5 mb-5">
                    @*<span class="text-decoration-line-through">$45.00</span>*@
                    <span> @Html.DisplayTextFor(m => m.Precio) USD</span>
                </div>
                <p class="lead">@Html.DisplayTextFor(m => m.Descripcion)</p>
                <div class="d-flex">
                    <a href="@Url.Action("Index","Tienda")" class="btn btn-danger w-50 text-center me-3">
                        <i class="fas fa-undo-alt"></i>Volver
                    </a>
                    @if (Session["Cliente"] != null)
                    {
                        <button class="btn btn-success agregarcarrito flex-md-shrink-0 w-50" type="button" data-IdProducto=" @Html.DisplayTextFor(m => m.IdProducto)">
                            <i class="fas fa-cart-plus"></i>Agregar al Carrito
                        </button>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>

      $(document).on("click", "button.agregarcarrito", function () {

            console.log($(this).data("IdProducto"))
            jQuery.ajax({
                    url: "@Url.Action("AgregarCarrito", "Tienda")",
                    type: "POST",
                    data: JSON.stringify({ IdProducto: $(this).data("IdProducto")}),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.Respuesta) {
                            MostrarCantidadCarrito();
                            @*swal({
                                title: "Agregar al carrito",
                                text: "¿Dessea ir al carrito?",
                                type: "success",
                                showCancelButton: true,
                                confirmButtonClass: "btn-primary",
                                confirmButtonText: "Si",
                                cancelButtonText: "No",
                                closeOnConfirm: true


                            }, function () {
                                window.Location.href = '@Url.Action("Carrito","Tienda")'
                            })*@
                            swal("","Agregado al Carrito", "succcess");
                        } else {
                            swal("", data.Mensaje, "warning");
                        }
                    }
             });

        })

    </script>
}

Carritode ComprasAdmi/Views/Tienda/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Compra con estilo</h1>
            <p class="lead fw-normal text-white-50 mb-0">Encuentra los mejores productos</p>
        </div>
    </div>
</header>
<!-- Section-->
<section >
    <div class="container-fluid px-5 my-5 ">
        <div class="row">
            <div class="col-sm-3">
                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Categorias
                            </div>
                            <div id="contenedor_categoria" class="card-body">
                               
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Marcas
                            </div>
                            <div id="contenedor_marca" class="card-body">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="d-grid gap-2">
                            <button id="btnfiltro" class="btn btn-outline-dark btn-blok" type="button">
                                <i class="fas fa-filter"></i>Aplicar Filtro
                            </button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-sm-9">
                <div id="contenedor_producto" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fancy Product</h5>
                                    <!-- Product price-->
                                    $40.00 - $80.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Special Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$20.00</span>
                                    $18.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@section scripts{
    <script>

        $(document).ready(function () {

            MostrarCategorias();
            MostrarProductos(0, 0)

        })

        function MostrarCategorias() {

            jQuery.ajax({
                url: "@Url.Action("ListarCategorias", "Tienda")",
                type: "Get",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_categoria").LoadingOverlay("hide");

                    $("<div>").addClass("from-check").append(
                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": "0", "id": "cx", "checked": "cheked" }),
                        $("<label>").addClass("form-check-label").text("Todos").attr({ "for": "cx" })
                    ).appendTo("#contenedor_categoria")

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("from-check").append(
                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": element.IdCategoria, "id": "c" + i }),
                            $("<label>").addClass("form-check-label").text(element.Descripcion).attr({ "for": "c" + i })
                        ).appendTo("#contenedor_categoria")

                    })
                    MostrarMarcas();

                },
                beforeSend: function () {
                    $("#contenedor_categoria").LoadingOverlay("show");

                }

            })


        }


        function MostrarMarcas() {
            var IdCategorias = $("input[name = categoria]:checked").val()
            jQuery.ajax({
                url: "@Url.Action("ListarMarcaProducto", "Tienda")",
                type: "Post",
                data: JSON.stringify({ IdCategoria: IdCategorias }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_marca").html("");
                    $("#contenedor_marca").LoadingOverlay("hide");

                    $("<div>").addClass("from-check").append(
                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": "0", "id": "mx", "checked": "cheked" }),
                        $("<label>").addClass("form-check-label").text("Todos").attr({ "for": "mx" })
                    ).appendTo("#contenedor_marca")

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("from-check").append(
                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": element.IdMarca, "id": "m" + i }),
                            $("<label>").addClass("form-check-label").text(element.Descripcion).attr({ "for": "m" + i })
                        ).appendTo("#contenedor_marca")

                    })

                },
                beforeSend: function () {
                    $("#contenedor_marca").LoadingOverlay("show");

                }

            })
        }

             $(document).on("change", "input[name = categoria]", function () {
                 MostrarMarcas();
             })


        function MostrarProductos(IdCategorias, IdMarcas) {
            jQuery.ajax({
                url: "@Url.Action("ListarProducto", "Tienda")",
                type: "Post",
                data: JSON.stringify({ IdCategoria: IdCategorias, IdMarca : IdMarcas }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_producto").html("");
                    $("#contenedor_producto").LoadingOverlay("hide");

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("col mb-5").append(
                            $("<div>").addClass("card h-100").append(
                                $("<img>").addClass("card-img-top").attr({ "src": "data:image/" + element.Extension + ";base64," + element.Base64 }),
                                $("<div>").addClass("card-body p-4").append(
                                    $("<div>").addClass("text-center").append(
                                        $("<h5>").addClass("fw-bolder").text(element.Nombre),
                                        "$" + element.Precio.toFixed(2) + "USD"
                                    )
                                ),

                                $("<div>").addClass("card-footer p-2 pt-0 border-top-0 bg-transparent").append(
                                    $("<div>").addClass("d-grid gap-2").append(
                                        @if (Session["Cliente"] != null)
                                         {
                                             @:$("<button>").addClass("btn btn-success mt-auto agregarcarrito").data("IdProducto", element.IdProducto).text("Agregar al Carrito"),

                                         }
                                        $("<a>").addClass("btn btn-dark mt-auto")
                                            .attr({ "href": "@Url.Action("DetalleProducto", "Tienda")" + "?IdProducto=" + element.IdProducto })
                                            .text("Ver Detalle")

                                    )
                                )

                            )
                        ).appendTo("#contenedor_producto")

                    })

                },
                beforeSend: function () {
                    $("#contenedor_producto").LoadingOverlay("show");

                }

            })

         }


        $("#btnfiltro").click(function () {
                 var IdCategorias = $("input[name = categoria]:checked").val()
                 var IdMarcas = $("input[name = marca]:checked").val()
                 MostrarProductos(IdCategorias, IdMarcas)

        })


        $(document).on("click", "button.agregarcarrito", function () {

            console.log($(this).data("IdProducto"))
            jQuery.ajax({
                    url: "@Url.Action("AgregarCarrito", "Tienda")",
                    type: "POST",
                    data: JSON.stringify({ IdProducto: $(this).data("IdProducto")}),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.Respuesta) {
                            MostrarCantidadCarrito();
                            swal({
                                title: "Agregar al carrito",
                                text: "¿Dessea ir al carrito?",
                                type: "success",
                                showCancelButton: true,
                                confirmButtonClass: "btn-primary",
                                confirmButtonText: "Sí",
                                cancelButtonText: "No",
                                closeOnConfirm: true
                            }, function () {
                                window.location.href = '@Url.Action("Carrito", "Tienda")';
                            })
                        } else {
                            swal("", data.Mensaje, "warning");
                        }
                    }
             });

        })

    </script>
    }

Carritode ComprasAdmi/Views/Tienda/MisCompras.cshtml
@model List<CapaEntidades.DetalleVenta>
@{
    ViewBag.Title = "MisCompras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3">
        <div class="col-sm-12">
            @{
                if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <div class="row mb-3">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body bg-light">
                                        <h6>ID TRANSACCION : @item.IdTransaccion</h6>
                                        <div class="table-responsive">
                                            <table class="table table-bordered">

                                                <thead>
                                                    <tr>
                                                        <th>Imagen</th>
                                                        <th>Producto</th>
                                                        <th>Precio Unitario</th>
                                                        <th>Cantidad</th>
                                                        <th>Sub Total</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="bg-white">
                                                    <tr>
                                                        <td>
                                                            <img class="card-img-top mb-5 mb-md-0" src="data:image / @item.oProducto.Extension;base64,@item.oProducto.Base64" style="width:120px;height:120px" />
                                                        </td>
                                                        <td valign="middle">
                                                            @item.oProducto.Nombre
                                                        </td>
                                                        <td valign="middle">
                                                           $ @item.oProducto.Precio USD
                                                        </td>
                                                        <td valign="middle">
                                                            @item.Cantidad
                                                        </td>
                                                        <td valign="middle">
                                                            S @item.Total USD
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                }
                 else
                 {
                    <div class="row mb-3">
                        <div class="col-sm-12 text-center">
                            <h1> No se encontro ninguna compra</h1>
                        </div>
                    </div>
                 }

            }
        </div>
    </div>

</div>

Carritode ComprasAdmi/Views/Tienda/PagoEfectuado.cshtml
@{
    ViewBag.Title = "PagoEfectuado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 text-center">
        <br /><br />
        @{
            if ((bool)ViewData["Status"])
            {
                <h1 class="text-success">Gracias!</h1>
                <i class="far fa-check-circle fa-9x text-success"></i>

                <h2 class="text-success">Su pago fue realizado con exito</h2>
                <h4> ID de Transacción : @ViewData["IdTransaccion"]</h4>

                <br />
                <a href="@Url.Action("Index","Tienda")" class="btn btn-primary">Volver a la Tienda</a>
            }
            else
            {

                <h1 class="text-danger">Lo Sentimos</h1>
                <i class="fas fa-exclamation-circle fa-9x text-danger"></i>
                <h2 class="text-danger">Su pago no fue realizado</h2>
                <br />
                <a href="@Url.Action("Index","Tienda")"  class="btn btn-primary">Volver a la Tienda</a>

            }
        }
    </div>
</div>